* Twenty-One
A game similar to Blackjack. There are two players, the dealer and the player. There is a single 52-card deck, not including Jokers. Both the dealer and the player each start with 2 cards from the deck. Each card has a numerical value to it. 2-10 are valued at face-value according to its number. Queen, King, and Jacks are all valued 10. An Ace can be either 1 or 11, depending on the sum of the values of the cards currently in hand. If the cards in hand summed with an 11-valued Ace is 21 or less, the Ace should be worth 11. Otherwise if the sum is over 21, it should be worth 1. Each Ace in a hand can be a different value than another ace in the same hand, they do not have to be the same.
The goal of the game is to draw cards from the deck to create the largest sum possible without exceeding 21. After both players have drawn cards, the highest hand that is 21 or less wins. Exceeding 21 leads to a "bust", or a losing condition. When the player has his or her turn, she may choose to "draw" or "stay". To draw is to draw a card from the deck to add to his hand. To stay is to stop drawing cards and allow the dealer to have his or her turn. When the dealer goes, he or she must draw cards until their sum is at least 17 or they bust. If the dealer has met this condition without busting, the two hands are then compared and the higher is the winner. Equal hands create a tie condition and the round must repeat.
